### PR TITLE
PostgreSQL support

### PR DESCRIPTION
**Pull request by pierre**
@kevinpostlewaite Could you review the queries and DDL?

### CODE REVIEW

**Comment by kevinpostlewaite** [comment]
Reviewed: looks good. I expect my changes to payment provider conversion report broke your changes: I can fix those up once the rest is ready to be merged.

**Comment by pierre** [comment]
> You've chosen magic numbers for null equivalency (e.g. -1 and 1-1-1970). You might consider making it explicit and defining constants like NULL_EQUIV_INT and NULL_EQUIV_DATE.

Yup, that would be good (although we had the same issue before with things like `'NULL'`).

> I can fix those up once the rest is ready to be merged.

Great! Your other PR was merged, can you submit a PR against the `postgresql-support` branch?

**Comment by pierre** [comment]
Any update:question:

**Comment by kevinpostlewaite** [comment]
No update, it looks like I have a bunch of analytics plugin work to do and I'll try to get it in then.

**Pull request merged**
